### ISSUE TITLE
GitHub Link does not work on Firefox

### ISSUE THREAD

**Issue by HiroAgustin** [marcintreder/adele#10]
Looks like using a button to wrap a link is not allowed: https://stackoverflow.com/questions/17253410/link-inside-a-button-not-working-in-firefox#17253457

This seems to be the line at fault: https://github.com/marcintreder/adele/blob/master/src/components/social/social.styles.jsx#L42

Site is awesome, thanks!

FF version: 57.0.4 
OSX version: 10.13.2

**Comment by marcintreder** [comment]
Should be fine now! Thank you for reporting!

**Comment by beatrix-bodo** [comment]
I noticed another broken link issue.
If I click on the link for Wordpress.Com Design Handbook (Automattic), it takes me to "https://dotcombrand.wordpress.com/index.html". That gives me a 404. Same result on Chrome, Firefox and Safari.
However, if I edit the url and remove "/index.html" from the end, [it works](https://dotcombrand.wordpress.com).
Let me know if I should open a new issue for this.
