### ISSUE TITLE
The script “npm run data-build” Error on windows

### ISSUE THREAD

**Issue by Caldis** [marcintreder/adele#20]
It seems like "fs.utimesSync" causes "invalid argument" error on Windows.
Perhaps "atime" or "mtime" has a different usage on Windows than MacOS.

The line at fault: 
https://github.com/marcintreder/adele/blob/master/tools/data-builder.js#L86

The screenshot of error: 
![image](https://user-images.githubusercontent.com/3529490/35340360-dcd2c61e-015d-11e8-83f2-c3b215a1c763.png)

OS Version：Windows 10

By the way, the "npm install" also causes eslint`s "linebreak-style" error.
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style-in-eslint-using

**Comment by marcintreder** [comment]
Oh:( Sorry about that! We'll take care of it! @michalstocki prepared an improved mechanism of generating data.JSON. I'll review it shortly.

In the meantime, feel free to re-open your PR without committing data.jSON. I'll generate it on my end and commit to the repo. Thank you for contributing!

**Comment by Caldis** [comment]
Hi @marcintreder I close my PR really because i forgot the test & generate the data.JSON. And few minutes later i got this ISSUE. 😂
I will reopen the PR, thanks for your help. 🎉 
Awesome collection of design systems , thanks !
