### ISSUE TITLE
Problem with installing app on Windows

### ISSUE THREAD

**Issue by MastalerzKamil** [marcintreder/adele#44]
I can't install app after clone. It gives me several errors familiar with `error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style` after typing `npm install`. Maybe that's why because I use Windows but I don't know why during installation :/. Someone knows why?

**Comment by marcintreder** [comment]
Hey! It seems that this due to some dependencies using mac specific file paths. I don't have a bandwidth to take care of it right now, but we're open for PRs. If you feel like it - give it a try! 🙌
