### ISSUE TITLE
Add Aurora design system (Government of Canada)

### ISSUE THREAD

**Issue by s-duffey** [marcintreder/adele#45]
Built by the Digital Collaboration Division in the Government of Canada, Aurora is a new design system that is currently in alpha. 

Aurora is open source, multi-disciplinary and free for anyone to use. 

See the design system here: https://gctools-outilsgc.github.io/design-system-code/

**Comment by marcintreder** [comment]
Great design system! I don't have a bandwidth to analyze it right now, but we're open for PRs! :)
